apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: training 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  
  resources:
    requests:
      storage: 100Gi