apiVersion: v1
kind: Pod
metadata:
  name: qwen-pull
  namespace: training
spec:
  containers:
  - name: qwen-pull
    image: huggingface/transformers-pytorch-gpu
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc